### ISSUE TITLE
panel启动失败

### ISSUE THREAD

**Issue by hejun041** [dockere/jd-base#66]
昨天都还好好的，重启panel报错
`internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'compression'
Require stack:
- /jd/panel/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/jd/panel/server.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/jd/panel/server.js' ]
}`

**Comment by hejun041** [comment]
> 昨天都还好好的，重启panel报错
> `internal/modules/cjs/loader.js:818
> throw err;
> ^
> 
> Error: Cannot find module 'compression'
> Require stack:
> 
> * /jd/panel/server.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>   at Module.require (internal/modules/cjs/loader.js:887:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/jd/panel/server.js:11:19)
>   at Module._compile (internal/modules/cjs/loader.js:999:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>   at Module.load (internal/modules/cjs/loader.js:863:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/jd/panel/server.js' ]
>   }`

解决了，我到镜像里面npm了一下，应该是不知道什么原因body-parser没找到
